# This is a basic workflow to help you get started with Actions

name: My First Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: hello-world-nginx:v1

      - name: Run Docker image
        uses: docker/run-action@v1
        with:
          image: hello-world-nginx:v1
          options: -p 8080:80
